CI : Pin setuptools on Windows
The recent release of setuptools 82.0.0 removed `pkg_resources`, which is required by our current version of Sphinx. https://setuptools.pypa.io/en/latest/history.html#v82-0-0

```
 File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\site-packages\sphinx\registry.py", line 24, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```