PathColumn : Add copy assignment operator for CellData
Without this, Clang complains :

```
error: definition of implicit copy assignment operator for 'CellData'
is deprecated because it has a user-declared copy constructor
[-Werror,-Wdeprecated-copy]
```