GraphEditor config : Fix error in location drop handler
When the drag originates outside Gaffer, `event.sourceWidget` is `None`, in which case we were getting the following error :

```
ERROR :   File "/home/john/dev/build/gaffer-1.4/startup/gui/graphEditor.py", line 253, in __dropLocationData
ERROR :     sourceEditor = event.sourceWidget.ancestor( GafferUI.Editor )
ERROR : AttributeError: 'NoneType' object has no attribute 'ancestor'
```

This had gone unnoticed before, because typically such events were being accepted by `__fileDragEnter()` first and never reached the location drop handler. But when the file is of an unhandled type, the file handler returns False and the location handler comes into play.