AnnotationsGadget : Work around MSVC bug
With the original code we were getting this compilation error :

```
C:\Users\John\dev\gaffer\src\GafferUI\AnnotationsGadget.cpp(694): error C2440: '<function-style-cast>': cannot convert from 'const GafferUI::AnnotationsGadget::schedulePlugValueSubstitutions::<lambda_865de2d9e4b3857c59238e0cbe33775b> *' to 'GafferUI::AnnotationsGadget::Ptr'
```

Looks like MSVC thought `this` was a pointer to the lambda and not to the AnnotationsGadget.