GafferDispatch : Fix job name scan on Windows
- On Windows filename().c_str() is a wchar_t so we need an extra conversion.
- Fixes MSVC "error C2664: 'long strtol(const char *,char **,int)': cannot convert argument 1 from 'const boost::filesystem::path::value_type *' to 'const char *'"