GraphEditorTest : Extend idle wait in `testAutomaticLayout()`
Automatic layout is performed in `preRender()`, so the assertions require that we have waited long enough for the window to have been redrawn. Although the old wait is more than sufficient for local testing, we have been getting periodic failures on Travis that we assume to be due to a machine under heavy load, and look like this :

```
======================================================================
FAIL: testAutomaticLayout (GafferUITest.GraphEditorTest.GraphEditorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/GafferHQ/gaffer/install/python/GafferUITest/GraphEditorTest.py", line 128, in testAutomaticLayout
    self.assertEqual( graphEditor.graphGadget().unpositionedNodeGadgets(), [] )
AssertionError: Lists differ: [GafferUI.StandardNodeGadget( ... != []
First list contains 2 additional elements.
First extra element 0:
GafferUI.StandardNodeGadget( "Gadget1" )
+ []
- [GafferUI.StandardNodeGadget( "Gadget1" ),
-  GafferUI.StandardNodeGadget( "Gadget" )]
```