IECoreArnoldPreview : Remove unused lambda captures
Fixes OSX build:
 src/GafferArnold/IECoreArnoldPreview/Renderer.cpp:2530:4: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]