Revert "Plug : Remove child outputs in `removeOutputs()`"
This reverts commit c9f53ef3cba48857e14ed167818581a36bf97019, which was merged in error because GitHub CI didn't run for PR #4616.

The commit caused the following test failure among others :

```
ERROR: testDeleteKeepsOrder (GafferImageTest.CatalogueTest.CatalogueTest)
Traceback (most recent call last):
   File "/__w/gaffer/gaffer/build/python/GafferImageTest/CatalogueTest.py", line 700, in testDeleteKeepsOrder
     del script["catalogue"]["images"][1]
Exception: Catalogue::imageNode : Unable to find image
```

This was caused by `Catalogue::imageRemoved()` trying to use plug connections to find the InternalImage for a removed Image plug, but all connections have been removed. More worrying, throwing an exception from this handler put Gaffer into a bad state where completely unrelated tests subsequently failed too. All the more reason to catch exceptions from slots automatically, as we will be doing for Gaffer 0.62.