GafferCortex : Fix explicit template instantiation errors
These occurred with Clang on OSX in C++11 mode, and were of the following form :

> error: explicit instantiation of 'GafferCortex::ParameterisedHolder' must occur in namespace 'GafferCortex'

More details of the C++ standard change that required this behaviour here :

https://wg21.cmeerw.net/cwg/issue275