ImageView : Revert texture converter change.
It creates the following error when viewing an empty Display :

RuntimeError: Exception : Unsupported color format.

We do need to fix the viewer mipmapping, but we should do so independently of the big change to our image bounds convention.