ImageWriterTest : Rewrite reference TIFF image
Without this, upgrading to OIIO 2.4 yields the following test failure :

```
FAIL: testTiffMetadata (GafferImageTest.ImageWriterTest.ImageWriterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/dev/build/gaffer-1.2/python/GafferImageTest/ImageWriterTest.py", line 845, in testTiffMetadata
    "tiff:Compression" : IECore.IntData( 8 )
  File "/home/john/dev/build/gaffer-1.2/python/GafferImageTest/ImageWriterTest.py", line 811, in __testMetadataDoesNotAffectPixels
    self.assertTrue( metaName in misledReaderMetadata.keys(), "Writer Metadata missing expected key \"{}\" set to \"{}\" : {}".format(metaName, str(expectedMetadata[metaName]), ext) )
AssertionError: False is not true : Writer Metadata missing expected key "IPTC:OriginatingProgram" set to "Gaf" : tif
```

There are layers of confusion here :

1. OIIO loads the value of `IPTC:OriginatingProgram` from the old file as "Gaf", although both `identify` and `hexdump` suggest it is "Gaffer 0.56.0.0". My assumption is that this was either due to a bug in the OIIO version used to write the file, or in OIIO 2.4 when reading the file. Or both.
2. OIIO 2.4 stopped writing IPTC fields to TIFF files by default, in https://github.com/OpenImageIO/oiio/pull/3316, apparently because it was buggy. This seems to add some weight to the assumptions in 1). This is the main cause of the test failure.
3. But, after using OIIO's `tiff:write_iptc` option to force the writing of IPTC metadata, the test _still fails_! Inspection with `identify -verbose` shows that _two_ `IPTC:OriginatingProgram` fields are written to the file in this case, one with the truncated "Gaf" value and one with the full expected value. My assumption is that when OIIO reads this file, the second one wins and then OIIO discards it because it matches the value of `Software` - see https://github.com/OpenImageIO/oiio/commit/aeecd8181c0667a98b3ae4db2c0ea5673e2ab534. Hence the test still fails.
4. A later OIIO commit claims to fix some IPTC bugs and suggests that `tiff:write_iptc` could become the default one day. See https://github.com/OpenImageIO/oiio/pull/3465.

Conclusion : OIIO's IPTC/TIFF handling is not currently to be trusted, and we're happier  that it defaults to off. We'll consider re-enabling it upon request, at which point we can perhaps dig a little deeper. But for now we just update the expected output and call it good enough.