CI : Fix error in release validation
I broke this in af40ec4ae0da84ec6530a60e1e47851f523a2840, resulting in this error for PRs made from forks :

```
Validation failed
Error: ERROR: arnold is missing from the archive
```

We are passing `--skipPaths arnold --skipPaths renderMan` in this case, so need to accumulate the arguments rather than let the second one clobber the first.