fixup! ShadingEngine : Update for OSL 1.14
This hopefully fixes the following compilation error on Windows :

```
 D:\a\gaffer\gaffer\src\GafferOSL\ShadingEngine.cpp(875): warning C4624: '`anonymous-namespace'::StringParameter': destructor was implicitly defined as deleted
D:\a\gaffer\gaffer\src\GafferOSL\ShadingEngine.cpp(893): warning C4624: '`anonymous-namespace'::DebugParameters': destructor was implicitly defined as deleted
```

This only happened when compiling with OSL 1.13, where `ustring` doesn't have a trivial destructor (just an empty one). But I think I'm a bit happy with the move away from using a `union` anyway.