Arnold Renderer : Do not supply global `render:` attributes
This is a temp commit to get the tests passing. I'm assuming we _do_ want global attributes passed to the renderer, so we'd either need to add support for Box2fData (after https://github.com/GafferHQ/gaffer/pull/4461 is merged) or to somehow indentify the "special case" `render:*` globals that should _not_ be passed through.

Without this, we would get the following:

```
======================================================================
ERROR: testRenderRegion (GafferArnoldTest.ArnoldRenderTest.ArnoldRenderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrewk/apps/gaffer/0.61.0.0dev/cent7.x86_64/cortex/10.3/gaffer/py2/python/GafferTest/TestCase.py", line 126, in __messageHandlerCleanup
    raise RuntimeError( "Unexpected message : " + failureHandler.levelAsString( message.level ) + " : " + message.context + " : " + message.message )
RuntimeError: Unexpected message : WARNING : setParameter : Unsupported data type "Box2fData" for name "render:cropWindow"
```