ShaderUI : Fix user defaults for parameter child plugs
Fixes the following test failure :

```
======================================================================
FAIL: testSplineParameterUserDefaults (GafferOSLUITest.OSLShaderUITest.OSLShaderUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/john/dev/build/gaffer/python/GafferOSLUITest/OSLShaderUITest.py", line 110, in testSplineParameterUserDefaults
    self.assertEqual( s["parameters"]["spline"]["interpolation"].getValue(), Gaffer.SplineDefinitionInterpolation.Linear )
AssertionError: 1 != Gaffer._Gaffer.SplineDefinitionInterpolation.Linear
```

This appears to have been broken by #2536, which was pull-requested before the test was added, but merged after the test had been merged. Something to bear in mind if we keep PRs open for a long time - the Travis results are only valid at the point they were run, and aren't to be trusted after subsequent changes to master.