InteractiveArnoldRenderTest : Fix intermittent failure on macOS
When testQuadLightTextureEdits is run on macOS it occasionally fails with:

```
File "/Users/runner/work/gaffer/gaffer/build/arnold/7.4/python/GafferArnoldTest/InteractiveArnoldRenderTest.py", line 349, in testQuadLightTextureEdits
    self.assertAlmostEqual( self._color4fAtUV( s["catalogue"], imath.V2f( 0.5 ) ).g, 0, delta = 0.01 )
AssertionError: 0.030833924189209938 != 0 within 0.01 delta (0.030833924189209938 difference)
```

Which looks like the green channel might just need a bit more time to converge, so we now wrap this assert in an assertEventually like the other asserts in this test.