SceneInspector : Fix Globals->Sets section
When clicking to select the objects in the set, the following error was being emitted :

```
File "/disk1/john/dev/build/gaffer/python/GafferSceneUI/SceneInspector.py", line 2150, in __buttonRelease
    GafferSceneUI.ContextAlgo.setSelectedPaths( context, IECore.PathMatcher( widget.paths ) )
    TypeError: 'set' object does not support indexing
```

In addition to the fix, we now use native PathMatcher operations for difference, intersection and size, avoiding slow python operations on sets of strings.