PathWidget : Work around WeakMethod error at shutdown.
This was occuring after generating the documentation screengrabs in Image Engine builds, yielding the following error :

```
terminate called after throwing an instance of 'IECore::Exception'
  what():  Traceback (most recent call last):
  File "/home/john/apps/gaffer/0.24.0.0dev/cent7.x86_64/cortex/9/gaffer/python/Gaffer/WeakMethod.py", line 64, in __call__
    raise ReferenceError( "Instance referenced by WeakMethod %s() no longer exists" % self.__method.__name__ )
ReferenceError: Instance referenced by WeakMethod __pathChanged() no longer exists
```

It's not totally clear why this happens in only IE builds - perhaps a PySide vs PyQt issue? In any case, we have a similar workaround in place in TextWidget, and it seems to do the trick here too.