PathListingWidget : Fix drag error dragging from certain columns.
With the addition of drag and drop from `PathListingWidget`, columns derived from `PathColumn` must set a default value for `canceller` in `*Data` methods to avoid the error :

python/GafferUI/PathListingWidget.py", line 681, in __dragBegin
    return self.getColumns()[index.column()].cellData( path ).value
TypeError: cellData() missing 1 required positional argument: 'canceller'