GafferArnold : Add missing GafferOSL binding import
GafferArnold makes use of OSL closure plugs. If the GafferOSL isn't
imported when using GafferArnold nodes in python, then the missing
plug bindings can result in errors such as:

```
File "python/GafferUI/PlugLayout.py", line 425, in __staticItemMetadataValue
    return cls.__metadataValue( parent, layoutName + ":customWidget:" + item + ":" + name )
TypeError: cannot concatenate 'str' and 'GraphComponent' objects
```