VisualiserTool : Add missing include
Without it, we see `ERROR : GLWidget : 0(14) : error C1503: undefined variable "FLT_EPSILON"` errors while using the VisualiserTool on Linux.