StringPlugTest : Adapt for changes in Python 3.8
Before 3.8, `expanduser()` would use `$HOME` if it was set, but in 3.8
and later that is ignored, and `$USERPROFILE` is preferred instead. Our
`bin/gaffer.cmd` wrapper sets `HOME` from `USERPROFILE` but replaces
backslashes with forward slashes. And `IECore::StringAlgo::substitute()`
uses `$HOME` on all platforms. So we were getting the following test failure :

```
Error: FAIL: testTildeExpansion (GafferTest.StringPlugTest.StringPlugTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\gaffer\gaffer\build\python\GafferTest\StringPlugTest.py", line 124, in testTildeExpansion
    self.assertEqual( n["out"].getValue(), os.path.expanduser( "~" ) )
AssertionError: 'C:/Users/runneradmin' != 'C:\\Users\\runneradmin'
- C:/Users/runneradmin
?   ^     ^
+ C:\Users\runneradmin
?   ^     ^
```

There may be a bigger question here about whether we should be using `USERPROFILE`
in `StringAlgo::substitute()` and possibly not even setting `HOME` on Windows,
but that can wait for another day.