USDShader : Make `std` namespace explicit
On Windows, this was causing a build error where it was ambiguous
whether a USD header should use a USD Boost method or standard library
method :

`error C2872: 'add_lvalue_reference<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const >': ambiguous symbol`