PlugValueWidgetTest : Fix handling of background updates
This fixes test failures that looked like this :

```
Traceback (most recent call last):
  File "D:\a\gaffer\gaffer\build\python\GafferUITest\PlugValueWidgetTest.py", line 453, in testContextTrackerUpdates
    self.waitForUpdate( widget )
  File "D:\a\gaffer\gaffer\build\python\GafferUITest\PlugValueWidgetTest.py", line 62, in waitForUpdate
    handler.assertCalled()
  File "D:\a\gaffer\gaffer\build\python\GafferTest\ParallelAlgoTest.py", line 92, in assertCalled
    self.receive( timeout )()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\gaffer\gaffer\build\python\GafferTest\ParallelAlgoTest.py", line 86, in receive
    raise AssertionError( "UIThread call not made within {} seconds".format( timeout ) )
AssertionError: UIThread call not made within 30.0 seconds
```

Our old approach of calling `waitForUpdate()` after running the code to trigger
the update was bogus - it was possible for the update to have finished before we
even got to calling `waitForUpdate()`. By triggering the update from _inside_ the
UIThreadCallHandler's scope we avoid this possibility.