3Delight RendererTest : Fix failure to parse NSI file
The tests affected by this were merged to `1.3_maintenance` where `.nsi` files is written as ASCII. But on main since f4170654798cb45c000ea477c5c3ca9488b22e60 we need to use the `.nsia` extension for ASCII, and `.nsi` is binary. This was giving us the following CI failure :

```
Error: ERROR: testUSDLightShaping (IECoreDelightTest.RendererTest.RendererTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/gaffer/gaffer/build/python/IECoreDelightTest/RendererTest.py", line 1316, in testUSDLightShaping
    nsi = self.__parseDict( self.__renderLights( lightSettings ) )
  File "/__w/gaffer/gaffer/build/python/IECoreDelightTest/RendererTest.py", line 1408, in __parseDict
    for i in f.readlines() :
  File "/__w/gaffer/gaffer/build/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 97: invalid continuation byte
```