ParameterisedHolder : Fix python exception handling and test.
The following error was occurring when running `GafferCortexTest.ParameterisedHolderTest.testParameterInvalidWhenParameterChangedRaises()` :

```
Traceback (most recent call last):
  File "/disk1/john/dev/build/gaffer/python/GafferCortexTest/ParameterisedHolderTest.py", line 1126, in testParameterInvalidWhenParameterChangedRaises
    self.assertRaises( RuntimeError, ph["parameters"]["driver"].setValue, 1 )
  File "/disk1/john/dev/build/gaffer/lib/python2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
SystemError: NULL result without error in PyObject_Call
```

Using `git bisect` the problem can be traced all the way back to e0ba6a176f2949a35cf148edc3d5d355543b1ea3, but inexplicably this hasn't been triggered on Travis until now.

We shouldn't have been allowing boost::python::error_already_set to propagate out into pure C++ code in ParameterisedHolderWrapper::parameterChanged(), since there is nothing pure C++ code can do to handle that exception, and it also leaves python in a state with a current exception for the next time we enter back in to it. We now use `translatePythonException()` to clear the python exception status and turn it into a pure C++ exception which can be handled in the standard way. This gets rid of the `SystemError` problem, leaving us to capture the expected message output in `testParameterInvalidWhenParameterChangedRaises()`.