GafferArnoldUI : use AtStringStruct
Without this change, Windows errors with :
ERROR : startup/gui/menus.py : Error loading Arnold module - "argument 4: <class 'TypeError'>: expected LP_AtStringStruct instance instead of AtStringReturn".
 Traceback (most recent call last):
  File "K:\build\gaffer\startup\gui\menus.py", line 119, in <module>
    import GafferArnoldUI
  File "K:\build\gaffer\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "K:\build\gaffer\arnold\7.1\python\GafferArnoldUI\__init__.py", line 41, in <module>
    from . import ArnoldShaderUI
  File "K:\build\gaffer\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "K:\build\gaffer\arnold\7.1\python\GafferArnoldUI\ArnoldShaderUI.py", line 400, in <module>
    __translateNodeMetadata( arnold.AiNodeEntryIteratorGetNext( nodeIt ) )
  File "K:\build\gaffer\arnold\7.1\python\GafferArnoldUI\ArnoldShaderUI.py", line 209, in __translateNodeMetadata
    defaultValue = __aiMetadataGetStr( nodeEntry, None, "help" )
  File "K:\build\gaffer\arnold\7.1\python\GafferArnoldUI\ArnoldShaderUI.py", line 61, in __aiMetadataGetStr
    if arnold.AiMetaDataGetStr( nodeEntry, paramName, name, value ) :
ctypes.ArgumentError: argument 4: <class 'TypeError'>: expected LP_AtStringStruct instance instead of AtStringReturn