Cycles Renderer : Remove unused private field
To fix the following Clang error :

```
src/GafferCycles/IECoreCyclesPreview/Renderer.cpp:4254:9: error: private field 'm_lastProgress' is not used [-Werror,-Wunused-private-field]
                float m_lastProgress;
```