WidgetAlgo : Fix `grab()` for PySide2/Qt5
It was emitting the following error :

```
TypeError: 'PySide2.QtGui.QPixmap.grabWindow' called with wrong argument types:
  PySide2.QtGui.QPixmap.grabWindow(int)
Supported signatures:
  PySide2.QtGui.QPixmap.grabWindow(quintptr, int = 0, int = 0, int = -1, int = -1)
```

Also documented the reason we can't update to use Qt 5's preferred screengrab functions, and must instead live with warning output.